### ISSUE TITLE
Failure since new deb released

### ISSUE THREAD

**Issue by dannystaple** [aquasecurity/trivy-repo#38]
The deb package for this was updated today.
Since then we are seeing the following failure on ubuntu latest:

```
Setting up trivy (0.51.3) ...
NEEDRESTART-VER: 3.5
NEEDRESTART-KCUR: 6.5.0-1021-azure
NEEDRESTART-KEXP: 6.5.0-1021-azure
NEEDRESTART-KSTA: 1
panic: 1 error occurred: checks/docker/update_instruction_alone.rego:48: rego_type_error: undefined function sh.parse_commands

goroutine 1 [running]:
github.com/aquasecurity/trivy/pkg/iac/rego.RegisterRegoRules(0xc00134ecc0)
	/home/runner/work/trivy/trivy/pkg/iac/rego/embed.go:46 +0x29c
github.com/aquasecurity/trivy/pkg/iac/rego.init.1()
	/home/runner/work/trivy/trivy/pkg/iac/rego/embed.go:30 +0x185
```

**Comment by dannystaple** [comment]
checking for other versions in the deb list shows only 1 version:
```
/# apt-cache policy trivy
trivy:
  Installed: (none)
  Candidate: 0.51.3
  Version table:
     0.51.3 500
        500 https://aquasecurity.github.io/trivy-repo/deb jammy/main amd64 Packages
```

We cannot use this as a way to fix/revert to previous version.

**Comment by dannystaple** [comment]
This issue is https://github.com/aquasecurity/trivy/issues/6771.
